apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpletimeservice
  labels:
    app: simpletimeservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpletimeservice
  template:
    metadata:
      labels:
        app: simpletimeservice
    spec:
      containers:
        - name: simpletimeservice
          image: 4592adarsh/particle41:4567
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: simpletimeservice
  labels:
    app: simpletimeservice
spec:
  type: ClusterIP
  selector:
    app: simpletimeservice
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
